name: pomodoro_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  linked_scroll_controller: ^0.2.0
  page_transition: ^2.0.9
  cloud_firestore: ^3.5.0
  intl: ^0.17.0
  flutter_riverpod: ^2.0.2
  sqflite: ^2.1.0+1
  json_annotation: ^4.7.0
  syncfusion_flutter_calendar: ^20.3.49
  date_picker_timeline: ^1.2.3
  infinite_scroll_tab_view: ^1.0.3
  flip_card: ^0.6.0
  percent_indicator: ^4.2.2
  carousel_slider: ^4.1.1
  circular_countdown_timer: ^0.2.3
  flutter_svg: ^1.1.6
  modal_bottom_sheet: ^2.1.2
  flutter_secure_storage: ^5.0.2
  form_field_validator: ^1.1.0
  shimmer: ^2.0.0
  image_picker: ^0.8.6
  dropdown_button2: ^1.9.2
  duration_picker: ^1.1.1
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_quill: ^6.1.12
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  freezed: ^2.1.1
  json_serializable: ^6.5.1



  flutter_lints: ^2.0.0



flutter:
  assets:
    - assets/icons/
    - assets/images/
    - translations/


  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_app3.png"
  min_sdk_android: 22