name: pomodoro_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  linked_scroll_controller: ^0.2.0
  page_transition: ^2.0.9
  cloud_firestore: ^3.5.0
  intl: ^0.17.0
  flutter_riverpod: ^2.0.2
  sqflite: ^2.1.0+1
  json_annotation: ^4.7.0
  syncfusion_flutter_calendar: ^20.3.49
  date_picker_timeline: ^1.2.3
  infinite_scroll_tab_view: ^1.0.3
  flip_card: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^2.1.1
  json_serializable: ^6.5.1



  flutter_lints: ^2.0.0



flutter:
  assets:
    - assets/icons/
    - assets/images/


  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 22